/* =====================================================================
 * data.js — Static content for Smart Clinic Pro
 * البيانات الثابتة: ملفات الأطباء الاحتياطية، آراء المرضى، الترجمات،
 * الاقتباسات الصحية، وفهرس البحث.
 * Loaded as a classic <script defer> BEFORE page.js — these consts live in
 * the shared global scope and are read by page.js (renderDoctors, applyi18n…).
 * Pure data only — no logic. Edit clinic text / translations here.
 * ===================================================================== */

/* ---------- Fallback doctor profiles (used when Supabase is empty/unavailable) ---------- */

  const fallbackDoctorProfiles = [
    {
      id: 'fallback-internal-sarah',
      email: 'sarah.mitchell@smartclinicpro.com',
      display_name: 'Dr. Sarah Mitchell',
      specialty: 'Internal Medicine',
      bio: 'Board-certified physician focused on preventive care, chronic disease management, and clear patient communication.',
      photo_url: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=400&fit=crop&crop=face',
      is_active: true,
    },
    {
      id: 'fallback-internal-michael',
      email: 'michael.osei@smartclinicpro.com',
      display_name: 'Dr. Michael Osei',
      specialty: 'Internal Medicine',
      bio: 'Experienced internist specializing in diagnostics, adult medicine, and long-term health planning.',
      photo_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
      is_active: true,
    },
    {
      id: 'fallback-dentistry-james',
      email: 'james.patel@smartclinicpro.com',
      display_name: 'Dr. James Patel',
      specialty: 'Dentistry',
      bio: 'Gentle dental specialist offering preventive, restorative, and cosmetic oral care.',
      photo_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face',
      is_active: true,
    },
    {
      id: 'fallback-dentistry-aisha',
      email: 'aisha.rahman@smartclinicpro.com',
      display_name: 'Dr. Aisha Rahman',
      specialty: 'Dentistry',
      bio: 'Dental care specialist focused on patient comfort, prevention, and long-term oral health.',
      photo_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
      is_active: true,
    },
    {
      id: 'fallback-ortho-elena',
      email: 'elena.volkov@smartclinicpro.com',
      display_name: 'Dr. Elena Volkov',
      specialty: 'Orthopedics',
      bio: 'Orthopedic specialist focused on joint care, mobility recovery, and sports injury treatment.',
      photo_url: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop&crop=face',
      is_active: true,
    },
    {
      id: 'fallback-ortho-robert',
      email: 'robert.chen@smartclinicpro.com',
      display_name: 'Dr. Robert Chen',
      specialty: 'Orthopedics',
      bio: 'Orthopedic physician specializing in mobility, injury recovery, and musculoskeletal wellness.',
      photo_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face',
      is_active: true,
    },
  ];

/* ---------- Testimonials · i18n translations · health quotes · search index ---------- */

  const testimonials = [
    {
      name: 'Emma Thompson',
      role: 'Patient since 2021',
      img: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'Smart Clinic Pro completely transformed my healthcare experience. Dr. Mitchell\'s thorough approach and the seamless online booking made everything so convenient. I cannot recommend this clinic enough!',
    },
    {
      name: 'Carlos Rivera',
      role: 'Patient since 2022',
      img: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'After years of dental anxiety, Dr. Patel made me actually look forward to appointments. The modern facility and kind staff create an environment unlike any other clinic I\'ve visited.',
    },
    {
      name: 'Linda Kovacs',
      role: 'Patient since 2020',
      img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'Dr. Volkov performed my knee replacement surgery with incredible precision. The recovery was faster than expected, and the follow-up care through their digital platform is exceptional.',
    },
    {
      name: 'Ahmed Hassan',
      role: 'Patient since 2023',
      img: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'The patient portal and chat system are game-changers. Being able to message my doctor between visits and have all my records digitally accessible gives me incredible peace of mind.',
    },
    {
      name: 'Sophia Chen',
      role: 'Patient since 2022',
      img: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'I switched to Smart Clinic Pro after years of frustrating healthcare experiences elsewhere. The difference is night and day — from booking to follow-up, everything just works.',
    },
    {
      name: 'Marcus Johnson',
      role: 'Patient since 2021',
      img: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'What sets Smart Clinic Pro apart is the genuine care from every staff member. Dr. Osei took time to explain my condition thoroughly, and the digital tools make managing my health effortless.',
    },
    {
      name: 'Fatima Al-Rashid',
      role: 'Patient since 2024',
      img: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'As a newcomer to the country, finding a clinic that truly cares was daunting. Smart Clinic Pro made me feel welcome from day one. Their multilingual staff and seamless digital experience are unmatched.',
    },
    {
      name: 'David Kim',
      role: 'Patient since 2022',
      img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'I have been to many clinics over the years, but none compare to the level of professionalism and care I receive here. The online booking saves me so much time, and the doctors are incredibly thorough.',
    },
    {
      name: 'Maria Gonzalez',
      role: 'Patient since 2023',
      img: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'The pediatric care at Smart Clinic Pro is outstanding. Dr. Rahman was wonderful with my children, explaining everything in a way that put them at ease. The whole family now comes here exclusively.',
    },
    {
      name: 'James Wilson',
      role: 'Patient since 2020',
      img: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'After struggling with chronic back pain for years, Dr. Volkov finally gave me a proper diagnosis and treatment plan. The integrated approach — combining physical therapy with digital follow-ups — made all the difference.',
    },
    {
      name: 'Aisha Patel',
      role: 'Patient since 2024',
      img: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'I love how easy it is to manage my entire healthcare journey from my phone. From booking appointments to viewing test results and chatting with my doctor, everything is just a few taps away. Truly modern healthcare.',
    },
    {
      name: 'Yuki Tanaka',
      role: 'Patient since 2023',
      img: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=60&h=60&fit=crop&crop=face',
      rating: 5,
      text: 'As someone who travels frequently, having access to my medical records digitally and being able to consult with my doctor through the chat feature has been invaluable. Smart Clinic Pro understands modern needs.',
    },
  ];

  const translations = {
    en: {
      nav_about: 'About', nav_doctors: 'Doctors', nav_booking: 'Booking', nav_contact: 'Contact',
      btn_login: 'Login', btn_signup: 'Sign Up', btn_book: 'Book Appointment', btn_doctors: 'Meet Our Doctors',
      btn_confirm_booking: 'Confirm Appointment', btn_done: 'Done',
      hero_badge: 'Now accepting new patients',
      hero_h1_line1: 'Your Health,', hero_h1_line2: 'Our Priority',
      hero_subtitle: 'World-class medical care, expert physicians, and a seamless digital experience — all in one place. Because you deserve the best.',
      stat_patients: 'Happy Patients', stat_doctors: 'Expert Doctors', stat_years: 'Years of Care', stat_rating: 'Patient Rating',
      section_about_badge: 'About Our Clinic', section_about_h: 'Where Compassion Meets Innovation',
      section_about_sub: 'Since 2010, Smart Clinic Pro has been transforming healthcare through cutting-edge technology, a patient-first philosophy, and a team of world-renowned specialists.',
      section_doctors_badge: 'Our Specialists', section_doctors_h: 'Expert Physicians You Can Trust',
      section_doctors_sub: 'Our board-certified specialists bring decades of experience and genuine compassion to every patient interaction.',
      section_booking_badge: 'Online Booking', section_booking_h: 'Schedule Your Appointment',
      section_booking_sub: 'Quick, easy, and secure. Book your appointment in under 2 minutes.',
      section_test_badge: 'Patient Testimonials', section_test_h: 'Voices of Our Patients',
      section_test_sub: 'Real stories from real patients. Their trust drives everything we do.',
      show_more: 'Show More',
      spec_internal: 'Internal Medicine', spec_dentistry: 'Dentistry', spec_ortho: 'Orthopedics',
      tab_all: 'All', tab_internal: 'Internal Medicine', tab_dentistry: 'Dentistry', tab_ortho: 'Orthopedics',
      form_name: 'Full Name', form_age: 'Age', form_gender: 'Gender', form_specialty: 'Specialty',
      form_date: 'Preferred Date', form_phone: 'Phone Number', form_notes: 'Notes / Symptoms',
      form_email: 'Email Address', form_password: 'Password', form_remember: 'Remember me',
      form_forgot: 'Forgot password?', form_first_name: 'First Name', form_last_name: 'Last Name',
      form_role: 'Register as', form_agree: 'I agree to the Terms of Service and Privacy Policy. An email verification will be sent to confirm your account.',
      gender_male: 'Male', gender_female: 'Female', gender_child: 'Child (under 12)',
      login_title: 'Welcome Back', login_sub: 'Sign in to your Smart Clinic Pro account',
      signup_title: 'Create Your Account', signup_sub: 'Join Smart Clinic Pro today',
      login_no_acc: "Don't have an account?", signup_has_acc: 'Already have an account?',

      overall_rating: 'Overall Rating', rating_care: 'Quality of Care', rating_staff: 'Staff Friendliness',
      rating_facility: 'Facility', rating_wait: 'Wait Time',
      about_feat1_title: 'JCI Accredited Excellence', about_feat2_title: 'Advanced Diagnostic Technology', about_feat3_title: 'Holistic Patient Care',
      svc_internal: 'Internal Medicine', svc_dentistry: 'Dentistry', svc_ortho: 'Orthopedics',
      booking_note: 'You will receive a confirmation email within 30 minutes.',
      success_title: 'Appointment Booked!', success_desc: "Your appointment has been submitted. You'll receive a confirmation email within 30 minutes once the doctor approves it.",
      cta_title: 'Ready to prioritize your health?', cta_sub: 'Join 12,000+ patients who trust Smart Clinic Pro.',
      footer_brand_desc: 'Delivering world-class healthcare with compassion, innovation, and the highest professional standards.',
      footer_links: 'Quick Links', footer_services: 'Specialties',
      hours_weekday: 'Mon–Sat: 8AM – 8PM', hours_emergency: 'Emergency: 24/7',
      scroll_down: 'Scroll to explore', tagline: 'Advanced Medical Care',
      chat_placeholder: 'Type a message...',
      search_placeholder: 'Search doctors, specialties, services...',
      contact_phone: 'Phone', contact_email: 'Email', contact_address: 'Address',
      float1_title: 'Appointment Confirmed', float1_sub: 'Dr. Sarah Mitchell • Today, 2 PM',
      float2_title: 'Top Rated Clinic',
      dd_about_rating: 'Our Ratings', dd_about_rating_sub: '4.9★ from 2,400+ patients',
      dd_about_services: 'Our Services', dd_about_services_sub: 'Comprehensive care solutions',
      dd_about_gallery: 'Gallery', dd_about_gallery_sub: 'Our world-class facilities',
      spec_internal_sub: 'General & preventive care', spec_dentistry_sub: 'Oral health specialists', spec_ortho_sub: 'Bone & joint specialists',
      svc_internal_sub: 'Diagnosis & prevention', svc_dentistry_sub: 'Complete oral care', svc_ortho_sub: 'Bone & joint care',
      about_feat1_desc: 'Internationally accredited by the Joint Commission, meeting the world\'s highest standards in patient safety and quality care.',
      about_feat2_desc: 'Equipped with the latest MRI, CT scans, and AI-assisted diagnostic tools for precision medicine and faster results.',
      about_feat3_desc: 'Every patient receives a personalized care plan, continuous follow-ups, and 24/7 digital access to their medical team.',
      form_name_ph: 'John Doe', form_age_ph: '35', form_phone_ph: '+1 (555) 000-0000', form_notes_ph: 'Briefly describe your symptoms or reason for visit...',
    },
    ar: {
      nav_about: 'عن العيادة', nav_doctors: 'الأطباء', nav_booking: 'الحجز', nav_contact: 'اتصل بنا',
      btn_login: 'تسجيل الدخول', btn_signup: 'إنشاء حساب', btn_book: 'احجز موعداً', btn_doctors: 'تعرف على أطبائنا',
      btn_confirm_booking: 'تأكيد الموعد', btn_done: 'تم',
      hero_badge: 'نقبل مرضى جدد الآن',
      hero_h1_line1: 'صحتك،', hero_h1_line2: 'أولويتنا',
      hero_subtitle: 'رعاية طبية عالمية المستوى، أطباء متخصصون، وتجربة رقمية سلسة — كل ذلك في مكان واحد. لأنك تستحق الأفضل.',
      stat_patients: 'مريض سعيد', stat_doctors: 'طبيب متخصص', stat_years: 'سنوات من الرعاية', stat_rating: 'تقييم المرضى',
      section_about_badge: 'عن عيادتنا', section_about_h: 'حيث تلتقي الرحمة بالابتكار',
      section_about_sub: 'منذ عام 2010، تُحوّل سمارت كلينيك برو مسار الرعاية الصحية من خلال أحدث التقنيات وفلسفة المريض أولاً وفريق من المتخصصين العالميين.',
      section_doctors_badge: 'متخصصونا', section_doctors_h: 'أطباء متخصصون يمكنك الوثوق بهم',
      section_doctors_sub: 'يجلب متخصصونا المعتمدون عقوداً من الخبرة والتعاطف الحقيقي لكل تفاعل مع المريض.',
      section_booking_badge: 'الحجز الإلكتروني', section_booking_h: 'جدول موعدك',
      section_booking_sub: 'سريع وسهل وآمن. احجز موعدك في أقل من دقيقتين.',
      section_test_badge: 'آراء المرضى', section_test_h: 'أصوات مرضانا',
      section_test_sub: 'قصص حقيقية من مرضى حقيقيين. ثقتهم تدفعنا إلى الأمام.',
      show_more: 'عرض المزيد',
      spec_internal: 'الطب الداخلي', spec_dentistry: 'طب الأسنان', spec_ortho: 'العظام والمفاصل',
      tab_all: 'الجميع', tab_internal: 'الطب الداخلي', tab_dentistry: 'طب الأسنان', tab_ortho: 'العظام',
      form_name: 'الاسم الكامل', form_age: 'العمر', form_gender: 'الجنس', form_specialty: 'التخصص',
      form_date: 'التاريخ المفضل', form_phone: 'رقم الهاتف', form_notes: 'ملاحظات / أعراض',
      form_email: 'البريد الإلكتروني', form_password: 'كلمة المرور', form_remember: 'تذكرني',
      form_forgot: 'نسيت كلمة المرور؟', form_first_name: 'الاسم الأول', form_last_name: 'اسم العائلة',
      form_role: 'سجّل كـ', form_agree: 'أوافق على شروط الخدمة وسياسة الخصوصية. سيُرسل إليك رسالة تحقق بالبريد الإلكتروني.',
      gender_male: 'ذكر', gender_female: 'أنثى', gender_child: 'طفل (أقل من 12)',
      login_title: 'مرحباً بعودتك', login_sub: 'سجّل الدخول إلى حسابك في سمارت كلينيك برو',
      signup_title: 'إنشاء حسابك', signup_sub: 'انضم إلى سمارت كلينيك برو اليوم',
      login_no_acc: 'ليس لديك حساب؟', signup_has_acc: 'لديك حساب بالفعل؟',

      overall_rating: 'التقييم العام', rating_care: 'جودة الرعاية', rating_staff: 'ودية الموظفين',
      rating_facility: 'المرافق', rating_wait: 'وقت الانتظار',
      about_feat1_title: 'اعتماد JCI للتميز', about_feat2_title: 'تقنيات تشخيصية متطورة', about_feat3_title: 'رعاية شاملة للمريض',
      svc_internal: 'الطب الداخلي', svc_dentistry: 'طب الأسنان', svc_ortho: 'العظام والمفاصل',
      booking_note: 'ستتلقى رسالة تأكيد بالبريد الإلكتروني خلال 30 دقيقة.',
      success_title: 'تم حجز الموعد!', success_desc: 'تم تقديم طلب موعدك. ستتلقى رسالة تأكيد بعد موافقة الطبيب.',
      cta_title: 'هل أنت مستعد لإعطاء صحتك الأولوية؟', cta_sub: 'انضم إلى أكثر من 12,000 مريض يثقون في سمارت كلينيك برو.',
      footer_brand_desc: 'تقديم رعاية صحية عالمية بالتعاطف والابتكار وأعلى المعايير المهنية.',
      footer_links: 'روابط سريعة', footer_services: 'التخصصات',
      hours_weekday: 'الاثنين–السبت: 8ص – 8م', hours_emergency: 'طوارئ: 24/7',
      scroll_down: 'مرر للاستكشاف', tagline: 'رعاية طبية متقدمة',
      chat_placeholder: 'اكتب رسالة...',
      search_placeholder: 'ابحث عن أطباء أو خدمات...',
      contact_phone: 'الهاتف', contact_email: 'البريد الإلكتروني', contact_address: 'العنوان',
      float1_title: 'الموعد مؤكد', float1_sub: 'د. سارة ميتشيل • اليوم، الساعة 2م',
      float2_title: 'العيادة الأعلى تقييماً',
      dd_about_rating: 'تقييماتنا', dd_about_rating_sub: '4.9★ من 2,400+ مريض',
      dd_about_services: 'خدماتنا', dd_about_services_sub: 'حلول رعاية شاملة',
      dd_about_gallery: 'معرض الصور', dd_about_gallery_sub: 'مرافقنا العالمية',
      spec_internal_sub: 'الرعاية العامة والوقائية', spec_dentistry_sub: 'متخصصو الصحة الفموية', spec_ortho_sub: 'متخصصو العظام والمفاصل',
      svc_internal_sub: 'التشخيص والوقاية', svc_dentistry_sub: 'الرعاية الفموية الكاملة', svc_ortho_sub: 'رعاية العظام والمفاصل',
      about_feat1_desc: 'معتمدة دولياً من لجنة المشتركة، وتلتزم بأعلى معايير العالم في سلامة المرضى وجودة الرعاية.',
      about_feat2_desc: 'مجهزة بأحدث أجهزة الرنين المغناطيسي والأشعة المقطعية وأدوات التشخيص بالذكاء الاصطناعي.',
      about_feat3_desc: 'كل مريض يحصل على خطة رعاية شخصية ومتابعات مستمرة ووصول رقمي 24/7 لفريقه الطبي.',
      form_name_ph: 'الاسم الكامل', form_age_ph: '35', form_phone_ph: '+966 5XX XXX XXXX', form_notes_ph: 'صف أعراضك أو سبب الزيارة...',
    },
    ru: {
      nav_about: 'О клинике', nav_doctors: 'Врачи', nav_booking: 'Запись', nav_contact: 'Контакты',
      btn_login: 'Войти', btn_signup: 'Регистрация', btn_book: 'Записаться', btn_doctors: 'Наши врачи',
      btn_confirm_booking: 'Подтвердить запись', btn_done: 'Готово',
      hero_badge: 'Принимаем новых пациентов',
      hero_h1_line1: 'Ваше здоровье,', hero_h1_line2: 'Наш приоритет',
      hero_subtitle: 'Медицинская помощь мирового класса, опытные врачи и удобный цифровой сервис — всё в одном месте. Потому что вы заслуживаете лучшего.',
      stat_patients: 'Довольных пациентов', stat_doctors: 'Врачей-специалистов', stat_years: 'Лет заботы', stat_rating: 'Рейтинг',
      section_about_badge: 'О нашей клинике', section_about_h: 'Там, где сострадание встречает инновации',
      section_about_sub: 'С 2010 года Smart Clinic Pro преобразует здравоохранение с помощью передовых технологий и команды всемирно известных специалистов.',
      section_doctors_badge: 'Наши специалисты', section_doctors_h: 'Врачи, которым можно доверять',
      section_doctors_sub: 'Наши сертифицированные специалисты привносят десятилетия опыта и искреннее сострадание в каждое взаимодействие с пациентом.',
      section_booking_badge: 'Онлайн-запись', section_booking_h: 'Запишитесь на приём',
      section_booking_sub: 'Быстро, легко и безопасно. Запишитесь на приём менее чем за 2 минуты.',
      section_test_badge: 'Отзывы пациентов', section_test_h: 'Голоса наших пациентов',
      section_test_sub: 'Реальные истории реальных пациентов. Их доверие движет всем, что мы делаем.',
      show_more: 'Показать ещё',
      spec_internal: 'Терапия', spec_dentistry: 'Стоматология', spec_ortho: 'Ортопедия',
      tab_all: 'Все', tab_internal: 'Терапия', tab_dentistry: 'Стоматология', tab_ortho: 'Ортопедия',
      form_name: 'Полное имя', form_age: 'Возраст', form_gender: 'Пол', form_specialty: 'Специальность',
      form_date: 'Предпочтительная дата', form_phone: 'Телефон', form_notes: 'Заметки / Симптомы',
      form_email: 'Электронная почта', form_password: 'Пароль', form_remember: 'Запомнить меня',
      form_forgot: 'Забыли пароль?', form_first_name: 'Имя', form_last_name: 'Фамилия',
      form_role: 'Зарегистрироваться как', form_agree: 'Я принимаю Условия использования и Политику конфиденциальности. Письмо с подтверждением будет отправлено на вашу почту.',
      gender_male: 'Мужской', gender_female: 'Женский', gender_child: 'Ребёнок (до 12 лет)',
      login_title: 'С возвращением', login_sub: 'Войдите в свой аккаунт Smart Clinic Pro',
      signup_title: 'Создать аккаунт', signup_sub: 'Присоединяйтесь к Smart Clinic Pro сегодня',
      login_no_acc: 'Нет аккаунта?', signup_has_acc: 'Уже есть аккаунт?',

      overall_rating: 'Общий рейтинг', rating_care: 'Качество помощи', rating_staff: 'Дружелюбность персонала',
      rating_facility: 'Оснащение', rating_wait: 'Время ожидания',
      about_feat1_title: 'Аккредитация JCI', about_feat2_title: 'Передовая диагностика', about_feat3_title: 'Комплексная помощь',
      svc_internal: 'Терапия', svc_dentistry: 'Стоматология', svc_ortho: 'Ортопедия',
      booking_note: 'Вы получите письмо с подтверждением в течение 30 минут.',
      success_title: 'Запись подтверждена!', success_desc: 'Ваш запрос на приём отправлен. Вы получите письмо с подтверждением после одобрения врача.',
      cta_title: 'Готовы позаботиться о своём здоровье?', cta_sub: 'Присоединяйтесь к 12 000+ пациентов, доверяющих Smart Clinic Pro.',
      footer_brand_desc: 'Медицинская помощь мирового класса с состраданием, инновациями и высочайшими профессиональными стандартами.',
      footer_links: 'Быстрые ссылки', footer_services: 'Специальности',
      hours_weekday: 'Пн–Сб: 8:00 – 20:00', hours_emergency: 'Скорая помощь: 24/7',
      scroll_down: 'Прокрутите, чтобы узнать больше', tagline: 'Передовая медицинская помощь',
      chat_placeholder: 'Введите сообщение...',
      search_placeholder: 'Поиск врачей, специальностей...',
      contact_phone: 'Телефон', contact_email: 'Эл. почта', contact_address: 'Адрес',
      float1_title: 'Приём подтверждён', float1_sub: 'Д-р Митчелл • Сегодня, 14:00',
      float2_title: 'Клиника с высшим рейтингом',
      dd_about_rating: 'Наш рейтинг', dd_about_rating_sub: '4.9★ от 2 400+ пациентов',
      dd_about_services: 'Наши услуги', dd_about_services_sub: 'Комплексные решения',
      dd_about_gallery: 'Галерея', dd_about_gallery_sub: 'Наши современные объекты',
      spec_internal_sub: 'Общая и профилактическая помощь', spec_dentistry_sub: 'Специалисты стоматологии', spec_ortho_sub: 'Специалисты по костям и суставам',
      svc_internal_sub: 'Диагностика и профилактика', svc_dentistry_sub: 'Полный уход за полостью рта', svc_ortho_sub: 'Уход за костями и суставами',
      about_feat1_desc: 'Международная аккредитация Объединённой комиссии, соответствие мировым стандартам безопасности пациентов.',
      about_feat2_desc: 'Оснащены новейшими МРТ, КТ и диагностическими инструментами на базе ИИ для точной медицины.',
      about_feat3_desc: 'Каждый пациент получает персональный план лечения, непрерывное наблюдение и круглосуточный цифровой доступ к своей медицинской команде.',
      form_name_ph: 'Иванов Иван', form_age_ph: '35', form_phone_ph: '+7 (XXX) XXX-XX-XX', form_notes_ph: 'Кратко опишите симптомы или причину визита...',
    }
  };

  const healthQuotes = [
    '"The greatest wealth is health." — Virgil',
    '"Take care of your body. It\'s the only place you have to live." — Jim Rohn',
    '"Health is not just about what you\'re eating. It\'s also about what you\'re thinking and saying." — Anonymous',
    '"An ounce of prevention is worth a pound of cure." — Benjamin Franklin',
    '"To keep the body in good health is a duty." — Buddha',
  ];

  const searchData = [
    { type: 'doctor', label: 'Dr. Sarah Mitchell', sub: 'Internal Medicine', href: '#doctors' },
    { type: 'doctor', label: 'Dr. James Patel', sub: 'Dentistry', href: '#doctors' },
    { type: 'doctor', label: 'Dr. Elena Volkov', sub: 'Orthopedics', href: '#doctors' },
    { type: 'doctor', label: 'Dr. Michael Osei', sub: 'Internal Medicine', href: '#doctors' },
    { type: 'doctor', label: 'Dr. Aisha Rahman', sub: 'Dentistry', href: '#doctors' },
    { type: 'doctor', label: 'Dr. Robert Chen', sub: 'Orthopedics', href: '#doctors' },
    { type: 'service', label: 'Internal Medicine', sub: 'General & preventive care', href: '#doctors' },
    { type: 'service', label: 'Dentistry', sub: 'Oral health specialists', href: '#doctors' },
    { type: 'service', label: 'Orthopedics', sub: 'Bone & joint specialists', href: '#doctors' },
    { type: 'page', label: 'Book Appointment', sub: 'Schedule your visit online', href: '#booking' },
    { type: 'page', label: 'About Smart Clinic Pro', sub: 'Our story and mission', href: '#about' },
    { type: 'page', label: 'Patient Testimonials', sub: 'What our patients say', href: '#testimonials' },
  ];

